export const LIST_ACTIVITY_REQUEST = 'LIST_ACTIVITY_REQUEST';
export const LIST_ACTIVITY_SUCCESS = 'LIST_ACTIVITY_SUCCESS';
export const LIST_ACTIVITY_FAILURE = 'LIST_ACTIVITY_FAILURE';

export const RETRIEVE_PROFILE_REQUEST = 'RETRIEVE_PROFILE_REQUEST';

export const SUBMIT_ACTIVITY_COMMENT = 'SUBMIT_ACTIVITY_COMMENT';
export const SUBMIT_ACTIVITY_LIKE = 'SUBMIT_ACTIVITY_LIKE';